// Runtime additions for Gaze Lab.
(function(){
  const cornerLabels={tl:'Alto sinistra',tr:'Alto destra',br:'Basso destra',bl:'Basso sinistra'};
  let activeCornerButton=null;
  function labelMode(){const x=document.getElementById('interactionModeLabel');return (x&&x.textContent||'').trim().toLowerCase()}
  function key(btn){return btn&&btn.dataset?btn.dataset.corner:''}
  function cornerBox(){let b=document.getElementById('cornerFeedback');if(b)return b;const sec=document.querySelector('.corner-grid')?.closest('.panel-card');b=document.createElement('div');b.id='cornerFeedback';b.className='readout corner-feedback';b.innerHTML='Punti estremi acquisiti: <strong id="cornerCount">0/4</strong>';sec?.appendChild(b);return b}
  function cornerMsg(msg){const b=cornerBox(),c=document.getElementById('cornerCount');if(c)c.textContent=document.querySelectorAll('.corner-btn.acquired').length+'/4';if(msg){let m=document.getElementById('cornerMessage');if(!m){m=document.createElement('div');m.id='cornerMessage';m.className='corner-message';b.appendChild(m)}m.textContent=msg}}
  function setActive(btn){document.querySelectorAll('.corner-btn').forEach(b=>b.classList.remove('active-corner'));activeCornerButton=btn;if(btn)btn.classList.add('active-corner');cornerMsg('Ora clicca sul video: '+(cornerLabels[key(btn)]||'punto selezionato')+'.')}
  function acquired(btn){if(!btn)return;const k=key(btn);btn.classList.remove('active-corner');btn.classList.add('acquired');if(!btn.textContent.includes('✓'))btn.textContent='✓ '+btn.textContent;cornerMsg('Acquisito: '+(cornerLabels[k]||'punto')+'.');const st=document.getElementById('statusTitle'),sx=document.getElementById('statusText'),sb=document.getElementById('statusBand');if(st&&sx&&sb){sb.className='status-band ready';st.textContent='Punto griglia acquisito';sx.textContent='Punto estremo della griglia salvato: '+(cornerLabels[k]||'punto')+'.'}activeCornerButton=null}
  function markClass(){const st=document.getElementById('videoStage');if(st)st.classList.toggle('marking',labelMode()!=='navigazione')}
  document.querySelectorAll('.corner-btn').forEach(btn=>btn.addEventListener('click',()=>setActive(btn),true));
  const oldMode=window.mode;window.mode=function(){if(oldMode)oldMode();markClass()};
  document.getElementById('videoStage')?.addEventListener('click',e=>{if(labelMode()==='navigazione')return;e.preventDefault();e.stopImmediatePropagation();const b=activeCornerButton;if(typeof window.clickCanvas==='function')window.clickCanvas(e);if(b)acquired(b);markClass()},true);
  document.getElementById('clearCornersBtn')?.addEventListener('click',()=>{document.querySelectorAll('.corner-btn').forEach(b=>{b.classList.remove('acquired','active-corner');b.textContent=b.textContent.replace(/^✓\s*/,'')});cornerMsg('Punti cancellati. Seleziona di nuovo il primo punto estremo della griglia.')});
  setInterval(markClass,250);cornerMsg();
})();

// Overlay correction: target checkbox controls only T, gaze is shown only with scia/fissazioni.
(function(){
  function id(x){return document.getElementById(x)}
  function has(name){try{return typeof window[name]==='function'}catch{return false}}
  function markLocal(ctx,p,col,l){if(!p)return;ctx.save();ctx.strokeStyle=col;ctx.fillStyle=col;ctx.lineWidth=2;ctx.beginPath();ctx.arc(p.x,p.y,7,0,Math.PI*2);ctx.stroke();ctx.beginPath();ctx.arc(p.x,p.y,2,0,Math.PI*2);ctx.fill();if(l){ctx.fillStyle='white';ctx.font='700 11px system-ui';ctx.fillText(l,p.x+7,p.y-8)}ctx.restore()}
  window.draw=function(){
    if(typeof S==='undefined')return;
    const c=id('overlayCanvas'),stage=id('videoStage');if(!c||!stage)return;
    const r=c.getBoundingClientRect(),k=devicePixelRatio||1;c.width=Math.max(1,r.width*k);c.height=Math.max(1,r.height*k);const ctx=c.getContext('2d');ctx.setTransform(k,0,0,k,0,0);ctx.clearRect(0,0,r.width,r.height);
    if(typeof toCan==='function'){
      Object.values(S.corners||{}).forEach(p=>markLocal(ctx,toCan(p),'#ffd166',''));
      if(['tl','tr','br','bl'].every(k=>S.corners&&S.corners[k])){ctx.save();ctx.strokeStyle='white';ctx.lineWidth=1.5;ctx.beginPath();['tl','tr','br','bl'].forEach((kk,i)=>{const p=toCan(S.corners[kk]);i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y)});ctx.closePath();ctx.stroke();ctx.restore()}
      const t=typeof recTime==='function'?recTime():0;
      if(id('showFixations')?.checked){(S.fix||[]).filter(f=>Math.abs(f.t-t)<2).forEach(f=>markLocal(ctx,toCan(f),'#ff9f43',''))}
      if(id('showTrail')?.checked){
        const recent=(S.gaze||[]).filter(g=>!g.bad&&g.t>=t-.45&&g.t<=t);ctx.save();ctx.strokeStyle='rgba(74,163,255,.72)';ctx.lineWidth=2;ctx.beginPath();let started=false;recent.forEach(g=>{const p=toCan(g);if(started)ctx.lineTo(p.x,p.y);else{ctx.moveTo(p.x,p.y);started=true}});ctx.stroke();ctx.restore();
        const g=typeof nearTime==='function'?nearTime(S.gaze||[],t):null;if(g&&!g.bad)markLocal(ctx,toCan(g),'#4aa3ff','G')
      }
      if(id('showTarget')?.checked){const ta=typeof nearTime==='function'?nearTime(S.targets||[],t):null;if(ta)markLocal(ctx,toCan(ta),'#fff176','T')}
    }
    if(typeof time==='function')time();
  };
})();

// Separate calibration window: start/end calibration, show all fixations in that window, suggest 9 pairs.
(function(){
  function ok(){return typeof S!=='undefined'&&typeof P!=='undefined'}
  function n(v){const x=Number(String(v??'').replace(',','.'));return Number.isFinite(x)?x:NaN}
  function fmt(x,d=3){return Number.isFinite(x)?x.toLocaleString('it-IT',{maximumFractionDigits:d,minimumFractionDigits:d}):'-'}
  function status(title,text,kind='ready'){const b=document.getElementById('statusBand'),t=document.getElementById('statusTitle'),s=document.getElementById('statusText');if(b&&t&&s){b.className='status-band '+kind;t.textContent=title;s.textContent=text}}
  function off(){return n(document.getElementById('syncOffsetMs')?.value)/1000||0}
  function recFromVideo(v){return (v?.currentTime||0)+off()}
  function calStart(){return n(document.getElementById('calStartSec')?.value)}
  function calEnd(){return n(document.getElementById('calEndSec')?.value)}
  function inCal(f){const a=calStart(),b=calEnd();return Number.isFinite(a)&&Number.isFinite(b)&&f.t>=Math.min(a,b)&&f.t<=Math.max(a,b)}
  function calFix(){return ok()?S.fix.filter(inCal):[]}
  function addUI(){const sec=document.querySelector('#calibrationPointSelect')?.closest('.panel-card');if(!sec||document.getElementById('calibrationWindowBox'))return;const box=document.createElement('div');box.id='calibrationWindowBox';box.innerHTML='<div class="divider-mini"></div><h3>Finestra video calibrazione</h3><p class="hint">Imposta inizio e fine della fase in cui vengono presentati i 9 punti. Qui sotto vedrai solo le fissazioni comprese in quella finestra.</p><div class="form-grid"><label>Inizio calibrazione (s)<input id="calStartSec" type="number" step="0.001" placeholder="inizio" /></label><label>Fine calibrazione (s)<input id="calEndSec" type="number" step="0.001" placeholder="fine" /></label></div><div class="button-row"><button id="setCalStartBtn" type="button">Imposta inizio calibrazione</button><button id="setCalEndBtn" type="button">Imposta fine calibrazione</button><button id="suggestCalPairsBtn" type="button" class="primary">Suggerisci 9 fissazioni</button></div><div class="readout">Fissazioni nella finestra: <strong id="calFixCount">0</strong></div><div class="calibration-stage" id="calibrationStage"><video id="calibrationVideo" controls playsinline></video><canvas id="calibrationOverlay"></canvas></div>';const target=document.getElementById('calibrationPointSelect')?.closest('label');sec.insertBefore(box,target);document.getElementById('setCalStartBtn').onclick=()=>{document.getElementById('calStartSec').value=fmt(recFromVideo(document.getElementById('sceneVideo')),3);syncCalVideo('start');drawCal()};document.getElementById('setCalEndBtn').onclick=()=>{document.getElementById('calEndSec').value=fmt(recFromVideo(document.getElementById('sceneVideo')),3);drawCal()};document.getElementById('suggestCalPairsBtn').onclick=suggestPairs;document.getElementById('calStartSec').onchange=()=>{syncCalVideo('start');drawCal()};document.getElementById('calEndSec').onchange=drawCal;document.getElementById('calibrationVideo').ontimeupdate=drawCal;document.getElementById('calibrationVideo').onloadedmetadata=drawCal;document.getElementById('calibrationOverlay').onclick=selectFix}
  function syncSource(){const src=document.getElementById('sceneVideo'),cv=document.getElementById('calibrationVideo');if(src&&cv&&src.src&&cv.src!==src.src)cv.src=src.src}
  function syncCalVideo(which){syncSource();const cv=document.getElementById('calibrationVideo');const t=which==='start'?calStart():recFromVideo(document.getElementById('sceneVideo'));if(cv&&Number.isFinite(t))cv.currentTime=Math.max(0,t-off())}
  function rect(){const st=document.getElementById('calibrationStage'),v=document.getElementById('calibrationVideo');const r=st.getBoundingClientRect(),vw=v.videoWidth||1600,vh=v.videoHeight||900,k=Math.min(r.width/vw,r.height/vh);return{x:(r.width-vw*k)/2,y:(r.height-vh*k)/2,k,vw,vh}}
  function can(p){const r=rect();return{x:r.x+p.x*r.k,y:r.y+p.y*r.k}}
  function clickVid(e){const c=document.getElementById('calibrationOverlay'),br=c.getBoundingClientRect(),r=rect(),x=e.clientX-br.left,y=e.clientY-br.top;if(x<r.x||y<r.y||x>r.x+r.vw*r.k||y>r.y+r.vh*r.k)return null;return{x:(x-r.x)/r.k,y:(y-r.y)/r.k}}
  function dot(ctx,p,color,label){const q=can(p);ctx.save();ctx.strokeStyle=color;ctx.fillStyle=color;ctx.lineWidth=2;ctx.beginPath();ctx.arc(q.x,q.y,8,0,Math.PI*2);ctx.stroke();ctx.beginPath();ctx.arc(q.x,q.y,3,0,Math.PI*2);ctx.fill();if(label){ctx.fillStyle='#fff';ctx.font='700 11px system-ui';ctx.fillText(label,q.x+9,q.y-7)}ctx.restore()}
  function grid(ctx){if(typeof H!=='function'||typeof proj!=='function')return;const h=H();if(!h)return;ctx.save();ctx.strokeStyle='rgba(255,255,255,.65)';ctx.lineWidth=1.2;for(const a of [0,.5,1]){let p1=proj(h,a,0),p2=proj(h,a,1),q1=can(p1),q2=can(p2);ctx.beginPath();ctx.moveTo(q1.x,q1.y);ctx.lineTo(q2.x,q2.y);ctx.stroke();p1=proj(h,0,a);p2=proj(h,1,a);q1=can(p1);q2=can(p2);ctx.beginPath();ctx.moveTo(q1.x,q1.y);ctx.lineTo(q2.x,q2.y);ctx.stroke()}ctx.restore()}
  function drawCal(){addUI();syncSource();const c=document.getElementById('calibrationOverlay');if(!c||!ok())return;const r=c.getBoundingClientRect(),d=devicePixelRatio||1;c.width=Math.max(1,Math.round(r.width*d));c.height=Math.max(1,Math.round(r.height*d));const ctx=c.getContext('2d');ctx.setTransform(d,0,0,d,0,0);ctx.clearRect(0,0,r.width,r.height);grid(ctx);const fx=calFix();const count=document.getElementById('calFixCount');if(count)count.textContent=fx.length;const chosen=new Set(Object.values(S.pairs||{}).map(p=>p.fx?.id));fx.forEach(f=>dot(ctx,f,chosen.has(f.id)?'#00c285':'#ff9f43',chosen.has(f.id)?'✓':''))}
  function selectFix(e){if(!ok())return;const p=clickVid(e);if(!p)return;let best=null,dist=1e9;calFix().forEach(f=>{const d=Math.hypot(f.x-p.x,f.y-p.y);if(d<dist){dist=d;best=f}});if(!best||dist>100)return status('Nessuna fissazione vicina','Clicca più vicino a una fissazione della finestra di calibrazione.','warn');assign(best)}
  function assign(fx){const hi=typeof Hinv==='function'?Hinv():null;if(!hi||typeof proj!=='function')return status('Griglia mancante','Segna prima i quattro estremi della griglia.','warn');const pt=P.find(p=>p.key===document.getElementById('calibrationPointSelect').value);const obs=proj(hi,fx.x,fx.y);S.pairs[pt.key]={pt,obs,fx};if(typeof render==='function')render();drawCal();status('Fissazione selezionata',pt.label+' associato alla fissazione '+fx.id+'.')}
  function suggestPairs(){const hi=typeof Hinv==='function'?Hinv():null;if(!ok()||!hi||typeof proj!=='function')return status('Griglia mancante','Segna prima i quattro estremi della griglia.','warn');const list=calFix();if(!list.length)return status('Finestra calibrazione vuota','Imposta inizio/fine calibrazione in modo da includere le fissazioni sui 9 punti.','warn');const used=new Set();P.forEach(pt=>{let best=null,bd=1e9,bobs=null;list.forEach(f=>{if(used.has(f.id))return;const obs=proj(hi,f.x,f.y);const d=obs?Math.hypot(obs.x-pt.x,obs.y-pt.y):1e9;if(d<bd){bd=d;best=f;bobs=obs}});if(best){used.add(best.id);S.pairs[pt.key]={pt,obs:bobs,fx:best}}});if(typeof render==='function')render();drawCal();status('Suggerimento completato','Associate automaticamente '+Object.keys(S.pairs).length+'/9 fissazioni. Puoi correggere cliccando manualmente quelle errate.')}
  const oldRender=window.render;window.render=function(){if(oldRender)oldRender();drawCal()};
  const currentDraw=window.draw;window.draw=function(){if(currentDraw)currentDraw();drawCal()};
  addUI();setInterval(drawCal,800);
})();

// Discreet guide mode: click the small bottom-right dot nine times to show hover explanations.
(function(){
  const explanations={'Distanza paziente-monitor (cm)':'Distanza tra occhi del paziente e schermo. Serve per convertire le posizioni in gradi visivi.','Larghezza area calibrazione (cm)':'Larghezza fisica della griglia di calibrazione. Serve per il grafico orizzontale in gradi visivi.','Altezza area calibrazione (cm)':'Altezza fisica della griglia di calibrazione. Serve per ricostruire lo spazio visivo verticale.','Finestra drive inizio (ms)':'Inizio della finestra precoce, rispetto all’onset del target, usata per stimare il drive motorio.','Finestra drive fine (ms)':'Fine della finestra precoce. Il drive è calcolato confrontando velocità del gaze e velocità del target.','Offset video-gaze (ms)':'Correzione manuale del disallineamento temporale tra video e dati gaze.','2. Griglia di calibrazione nel video':'Definisce lo spazio del task cliccando i quattro punti estremi della griglia di calibrazione.','3. Correzione su fissazioni':'Associa punti target reali e fissazioni osservate per correggere il gaze.','4. Target e trial':'Rileva il target bianco nel video e segmenta i movimenti laterali in trial.','Soglia bianco':'Soglia luminosa usata per rilevare il target bianco.','Passo rilevamento (s)':'Intervallo tra i frame analizzati. Più è piccolo, più il rilevamento è preciso ma lento.','Traccia orizzontale rispetto al centro':'Mostra gaze e target rispetto al centro della griglia: centro=0, sinistra=-1, destra=+1.','Gradi visivi':'Grafico in gradi visivi, disponibile se sono note dimensioni fisiche e distanza.','Misura normalizzata':'Grafico normalizzato: centro=0, estremo sinistro=-1, estremo destro=+1.','Report direzionale':'Sintesi del confronto fra drive verso destra e verso sinistra, controllando l’ampiezza.','Condizioni':'Riepilogo aggregato per direzione e ampiezza.','Trial analizzati':'Tabella dei singoli trial con onset, direzione, ampiezza, drive e qualità.','Finestra video calibrazione':'Video separato che mostra solo le fissazioni comprese tra inizio e fine calibrazione.','Inizio calibrazione (s)':'Tempo, in secondi, in cui inizia la fase dei 9 punti di calibrazione.','Fine calibrazione (s)':'Tempo, in secondi, in cui termina la fase dei 9 punti di calibrazione.','Suggerisci 9 fissazioni':'Associa automaticamente a ogni punto della griglia la fissazione più vicina nella finestra di calibrazione.'};
  function clean(t){return String(t||'').replace(/✓/g,'').replace(/\s+/g,' ').trim()}
  function activate(){localStorage.setItem('gazeLabGuide','1');document.body.classList.add('guide-on');document.querySelectorAll('h2,h3,label,button').forEach(node=>{if(node.dataset.guideReady)return;const direct=Array.from(node.childNodes).filter(n=>n.nodeType===3).map(n=>n.textContent).join(' ');const help=explanations[clean(direct||node.textContent)]||explanations[clean(node.textContent)];if(!help)return;node.dataset.guideReady='1';node.title=help;const dot=document.createElement('span');dot.className='guide-help-dot';dot.textContent='?';dot.title=help;node.appendChild(dot)})}
  function install(){let count=0,last=0,btn=document.createElement('button');btn.id='guideActivator';btn.type='button';btn.textContent='·';btn.setAttribute('aria-label','attiva guida');btn.onclick=()=>{const now=Date.now();if(now-last>2500)count=0;last=now;if(++count>=9){count=0;activate()}};document.body.appendChild(btn)}
  const style=document.createElement('style');style.textContent='#overlayCanvas{pointer-events:none!important}.video-stage.marking{cursor:crosshair}.video-stage.marking video{cursor:crosshair}.corner-btn.active-corner{outline:3px solid rgba(0,105,201,.28);border-color:#0069c9}.corner-btn.acquired{background:#e3f5ef;border-color:#07856f;color:#086750}.corner-feedback{padding:8px 10px;border:1px dashed #bfd0da;border-radius:9px;background:#fbfdfe}.corner-message{margin-top:4px;color:#087f7a;font-weight:700}.divider-mini{height:1px;background:#d7e0e5;margin:14px 0}.calibration-stage{position:relative;width:100%;aspect-ratio:16/9;background:#111;border-radius:10px;overflow:hidden;margin-top:10px}.calibration-stage video,.calibration-stage canvas{position:absolute;inset:0;width:100%;height:100%}.calibration-stage video{object-fit:contain}.calibration-stage canvas{pointer-events:auto}#guideActivator{position:fixed;right:8px;bottom:8px;width:14px;height:14px;min-height:0;padding:0;border:0;border-radius:50%;background:rgba(0,0,0,.14);color:rgba(0,0,0,.25);font-size:10px;line-height:10px;z-index:9999}#guideActivator:hover{background:rgba(0,0,0,.28);color:#fff}.guide-on [data-guide-ready]{cursor:help;text-decoration:underline dotted #0069c9;text-underline-offset:3px}.guide-help-dot{display:inline-flex;align-items:center;justify-content:center;margin-left:5px;width:14px;height:14px;border-radius:50%;background:#e8f2ff;color:#0069c9;font-size:10px;font-weight:800}';document.head.appendChild(style);install();if(localStorage.getItem('gazeLabGuide')==='1')setTimeout(activate,200);
})();
