// Scrolling horizontal saccade amplitude plot.
(function(){
  const $=id=>document.getElementById(id);
  const state={gaze:[],saccades:[]};
  function n(v){const x=Number(String(v??'').replace(',','.'));return Number.isFinite(x)?x:NaN}
  function clean(k){return String(k||'').toLowerCase().replace(/[^a-z0-9]/g,'')}
  function val(row,names){const keys=Object.keys(row||{});for(const name of names){if(row[name]!==undefined&&row[name]!=='')return row[name];const k=keys.find(x=>clean(x)===clean(name));if(k&&row[k]!=='')return row[k]}return ''}
  function parseCsv(txt){if(!txt)return[];const rows=[];let row=[],s='',q=false;for(let i=0;i<txt.length;i++){const c=txt[i],nx=txt[i+1];if(c==='"'){if(q&&nx==='"'){s+='"';i++}else q=!q;continue}if(c===','&&!q){row.push(s);s='';continue}if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&nx==='\n')i++;row.push(s);if(row.some(x=>x.trim()))rows.push(row);row=[];s='';continue}s+=c}row.push(s);if(row.some(x=>x.trim()))rows.push(row);if(!rows.length)return[];const head=rows[0].map(x=>x.trim());return rows.slice(1).map(r=>Object.fromEntries(head.map((k,i)=>[k,(r[i]??'').trim()]))) }
  function sec(v,t0){const x=n(v);if(!Number.isFinite(x))return NaN;if(Number.isFinite(t0))return (x-t0)/1e9;return x>1e6?x/1e9:x}
  function pick(files,name){name=name.toLowerCase();return files.find(f=>f.name.toLowerCase()===name)||files.find(f=>(f.webkitRelativePath||'').toLowerCase().endsWith('/'+name))}
  async function load(ev){const files=[...(ev.target.files||[])];const gazeFile=pick(files,'gaze.csv'),sacFile=pick(files,'saccades.csv'),evFile=pick(files,'events.csv');if(!gazeFile||!sacFile){state.gaze=[];state.saccades=[];draw();return}const events=parseCsv(evFile?await evFile.text():'');const begin=events.find(r=>/begin/i.test(val(r,['name','event','type'])||''));const t0=begin?n(val(begin,['timestamp [ns]','timestamp_ns','timestamp'])):NaN;state.gaze=parseCsv(await gazeFile.text()).map((r,i)=>({t:sec(val(r,['timestamp [ns]','timestamp_ns','timestamp']),t0)||i/200,x:n(val(r,['gaze x [px]','gaze_x_px','scene_camera_frame_pixel_x','gaze_point_2d_x']))})).filter(p=>Number.isFinite(p.t)&&Number.isFinite(p.x)).sort((a,b)=>a.t-b.t);state.saccades=parseCsv(await sacFile.text()).map(r=>({start:sec(val(r,['start timestamp [ns]','start_timestamp_ns']),t0),end:sec(val(r,['end timestamp [ns]','end_timestamp_ns']),t0)})).filter(s=>Number.isFinite(s.start)&&Number.isFinite(s.end));draw()}
  function time(){return (($('sceneVideo')&&$('sceneVideo').currentTime)||0)+n(($('syncOffsetMs')&&$('syncOffsetMs').value)||0)/1000}
  function nearest(t){if(!state.gaze.length)return null;let lo=0,hi=state.gaze.length-1;while(lo<hi){const m=(lo+hi)>>1;if(state.gaze[m].t<t)lo=m+1;else hi=m}const a=state.gaze[lo],b=state.gaze[Math.max(0,lo-1)];return !b?a:Math.abs(a.t-t)<Math.abs(b.t-t)?a:b}
  function amp(s){const a=nearest(s.start),b=nearest(s.end);if(!a||!b)return null;const dx=b.x-a.x;return Number.isFinite(dx)?{t:(s.start+s.end)/2,dx,abs:Math.abs(dx)}:null}
  function draw(){const c=$('degPlot');if(!c)return;const box=c.getBoundingClientRect(),dpr=devicePixelRatio||1,w=Math.max(500,box.width||900),h=300;c.width=w*dpr;c.height=h*dpr;c.style.height=h+'px';const ctx=c.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);ctx.fillStyle='#fbfdfe';ctx.fillRect(0,0,w,h);ctx.strokeStyle='#d7e0e5';ctx.lineWidth=1;for(let i=0;i<=4;i++){const y=28+i*(h-58)/4;ctx.beginPath();ctx.moveTo(52,y);ctx.lineTo(w-16,y);ctx.stroke()}ctx.fillStyle='#5d6c76';ctx.font='12px system-ui';ctx.fillText('Ampiezza orizzontale effettiva delle saccadi, px',52,18);if(!state.saccades.length||!state.gaze.length){ctx.fillText('Carica i dati per visualizzare il tracciato.',52,54);return}const now=time(),win=12,t0=now-win/2,t1=now+win/2,all=state.saccades.map(amp).filter(Boolean),vis=all.filter(a=>a.t>=t0&&a.t<=t1),max=Math.max(40,...vis.map(a=>a.abs));const x0=52,x1=w-16,y0=h/2,plotH=h-70,X=t=>x0+(t-t0)/(t1-t0)*(x1-x0),Y=v=>y0-(v/max)*(plotH/2);ctx.strokeStyle='#8fa3af';ctx.beginPath();ctx.moveTo(x0,y0);ctx.lineTo(x1,y0);ctx.stroke();ctx.fillText('destra +',8,38);ctx.fillText('sinistra -',8,h-28);ctx.strokeStyle='#0069c9';ctx.lineWidth=2;ctx.beginPath();let started=false;vis.forEach(a=>{const x=X(a.t),y=Y(a.dx);if(!started){ctx.moveTo(x,y);started=true}else ctx.lineTo(x,y)});if(started)ctx.stroke();vis.forEach(a=>{const x=X(a.t),y=Y(a.dx);ctx.strokeStyle=a.dx>=0?'#087f7a':'#b43b3b';ctx.beginPath();ctx.moveTo(x,y0);ctx.lineTo(x,y);ctx.stroke();ctx.fillStyle=ctx.strokeStyle;ctx.beginPath();ctx.arc(x,y,3,0,Math.PI*2);ctx.fill()});const cx=X(now);ctx.strokeStyle='#162027';ctx.setLineDash([4,4]);ctx.beginPath();ctx.moveTo(cx,24);ctx.lineTo(cx,h-28);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#162027';ctx.fillText('tempo video',Math.min(cx+6,w-92),36);ctx.fillStyle='#5d6c76';ctx.fillText(t0.toFixed(1)+' s',x0,h-8);ctx.fillText(t1.toFixed(1)+' s',x1-44,h-8);ctx.fillText('±'+Math.round(max)+' px',8,18)}
  function init(){const f=$('folderInput'),v=$('sceneVideo'),off=$('syncOffsetMs');if(f)f.addEventListener('change',load);if(v){v.addEventListener('timeupdate',draw);v.addEventListener('seeked',draw)}if(off)off.addEventListener('input',draw);window.addEventListener('resize',draw);draw()}
  document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init();
})();
