const $=id=>document.getElementById(id);
const S={gaze:[],fix:[],sac:[],blink:[],events:[],targets:[],trials:[],results:[],corners:{},pairs:{},model:null,mode:'nav',corner:null,taskStart:NaN,url:''};
const P=[['tl','Alto sinistra',0,0],['tc','Alto centro',.5,0],['tr','Alto destra',1,0],['cr','Centro destra',1,.5],['c','Centro',.5,.5],['cl','Centro sinistra',0,.5],['bl','Basso sinistra',0,1],['bc','Basso centro',.5,1],['br','Basso destra',1,1]].map(([key,label,x,y])=>({key,label,x,y}));
function init(){P.forEach(p=>{let o=document.createElement('option');o.value=p.key;o.textContent=p.label;$('calibrationPointSelect').appendChild(o)});$('folderInput').onchange=loadFolder;$('videoInput').onchange=e=>e.target.files[0]&&loadVideo(e.target.files[0]);document.querySelectorAll('.corner-btn').forEach(b=>b.onclick=()=>{S.mode='corner';S.corner=b.dataset.corner;mode()});$('clearCornersBtn').onclick=()=>{S.corners={};draw();};$('setTaskStartBtn').onclick=()=>{S.taskStart=recTime();$('taskStartLabel').textContent=f(S.taskStart,3)+' s'};$('calibrationClickModeBtn').onclick=()=>{S.mode='cal';mode()};$('fitCalibrationBtn').onclick=fitCal;$('clearCalibrationBtn').onclick=()=>{S.pairs={};S.model=null;spatial();draw();};$('detectTargetsBtn').onclick=detect;$('analyzeBtn').onclick=()=>{analyze();render()};$('overlayCanvas').onclick=clickCanvas;$('sceneVideo').ontimeupdate=()=>{time();draw();plots()};$('sceneVideo').onplay=loop;$('sceneVideo').onpause=()=>cancelAnimationFrame(S.raf);['showTrail','showFixations','showTarget','syncOffsetMs','viewingDistanceCm','monitorWidthCm','monitorHeightCm'].forEach(id=>$(id)?.addEventListener('change',()=>{spatial();draw();plots()}));window.onresize=draw;render();}
async function loadFolder(e){try{let files=[...e.target.files],F=n=>files.find(x=>x.name.toLowerCase()==n||(x.webkitRelativePath||'').toLowerCase().endsWith('/'+n));let g=F('gaze.csv');if(!g)throw Error('gaze.csv non trovato');let ev=csv(await txt(F('events.csv')));let t0=(ev.find(r=>/begin/i.test(val(r,['name','event','type'])||''))||{})['timestamp [ns]'];t0=num(t0);S.events=ev;S.gaze=parseGaze(csv(await g.text()),t0);S.fix=parseFix(csv(await txt(F('fixations.csv'))),t0);S.sac=parseIntv(csv(await txt(F('saccades.csv'))),t0);S.blink=parseIntv(csv(await txt(F('blinks.csv'))),t0);markBad();let v=files.find(x=>/\.(mp4|mov|webm|m4v)$/i.test(x.name));if(v)loadVideo(v);setStatus('ready','Dati caricati',`${S.gaze.length} gaze, ${S.fix.length} fissazioni, ${S.sac.length} saccadi, ${S.blink.length} blink.`);spatial();render();}catch(err){setStatus('bad','Errore',err.message)}}
async function txt(f){return f?await f.text():''}function csv(t){if(!t)return[];let rows=[],r=[],s='',q=false;for(let i=0;i<t.length;i++){let c=t[i],n=t[i+1];if(c=='"'){if(q&&n=='"'){s+='"';i++}else q=!q;continue}if(c==','&&!q){r.push(s);s='';continue}if((c=='\n'||c=='\r')&&!q){if(c=='\r'&&n=='\n')i++;r.push(s);if(r.some(x=>x.trim()))rows.push(r);r=[];s='';continue}s+=c}r.push(s);if(r.some(x=>x.trim()))rows.push(r);if(!rows.length)return[];let h=rows[0].map(x=>x.trim());return rows.slice(1).map(c=>Object.fromEntries(h.map((k,i)=>[k,(c[i]??'').trim()])))}
function val(r,a){let ks=Object.keys(r||{});for(let n of a){if(r[n]!==undefined&&r[n]!=='')return r[n];let k=ks.find(k=>k.toLowerCase().replace(/[^a-z0-9]/g,'')==n.toLowerCase().replace(/[^a-z0-9]/g,''));if(k&&r[k]!=='')return r[k]}}function num(x){let n=Number(String(x??'').replace(',','.'));return isFinite(n)?n:NaN}function sec(ns,t0){return isFinite(ns)&&isFinite(t0)?(ns-t0)/1e9:isFinite(ns)?(ns>1e6?ns/1e9:ns):NaN}
function parseGaze(rows,t0){return rows.map((r,i)=>({t:sec(num(val(r,['timestamp [ns]','timestamp_ns'])),t0)||i/200,x:num(val(r,['gaze x [px]','gaze_x_px','scene_camera_frame_pixel_x','gaze_point_2d_x'])),y:num(val(r,['gaze y [px]','gaze_y_px','scene_camera_frame_pixel_y','gaze_point_2d_y'])),worn:num(val(r,['worn'])),bad:false,nx:NaN,dx:NaN,nv:NaN,dv:NaN})).filter(x=>isFinite(x.t)).sort((a,b)=>a.t-b.t)}
function parseFix(rows,t0){return rows.map((r,i)=>{let a=sec(num(val(r,['start timestamp [ns]','start_timestamp_ns'])),t0),b=sec(num(val(r,['end timestamp [ns]','end_timestamp_ns'])),t0);return{id:i+1,t:isFinite(a+b)?(a+b)/2:a,start:a,end:b,x:num(val(r,['fixation x [px]','fixation_x_px','x [px]'])),y:num(val(r,['fixation y [px]','fixation_y_px','y [px]'])),dur:num(val(r,['duration [ms]','duration_ms']))}}).filter(x=>isFinite(x.t)&&isFinite(x.x)&&isFinite(x.y))}
function parseIntv(rows,t0){return rows.map(r=>({start:sec(num(val(r,['start timestamp [ns]','start_timestamp_ns'])),t0),end:sec(num(val(r,['end timestamp [ns]','end_timestamp_ns'])),t0)})).filter(x=>isFinite(x.start)&&isFinite(x.end))}
function markBad(){S.gaze.forEach(g=>g.bad=(!isFinite(g.x)||!isFinite(g.y)||(isFinite(g.worn)&&g.worn<.5)||S.sac.some(s=>g.t>=s.start-.008&&g.t<=s.end+.008)||S.blink.some(b=>g.t>=b.start-.008&&g.t<=b.end+.008)))}
function loadVideo(file){if(S.url)URL.revokeObjectURL(S.url);S.url=URL.createObjectURL(file);$('sceneVideo').src=S.url}
function rect(){let r=$('videoStage').getBoundingClientRect(),v=$('sceneVideo'),vw=v.videoWidth||1600,vh=v.videoHeight||900,k=Math.min(r.width/vw,r.height/vh);return{x:(r.width-vw*k)/2,y:(r.height-vh*k)/2,k,vw,vh}}
function toVid(e){let r=$('overlayCanvas').getBoundingClientRect(),p=rect(),x=e.clientX-r.left,y=e.clientY-r.top;if(x<p.x||y<p.y||x>p.x+p.vw*p.k||y>p.y+p.vh*p.k)return null;return{x:(x-p.x)/p.k,y:(y-p.y)/p.k}}function toCan(p){let r=rect();return{x:r.x+p.x*r.k,y:r.y+p.y*r.k}}
function clickCanvas(e){let p=toVid(e);if(!p)return;if(S.mode=='corner'){S.corners[S.corner]=p;S.mode='nav';spatial();render();return}if(S.mode=='cal'){let fx=nearFix(p);if(!fx)return setStatus('warn','Nessuna fissazione vicina','Clicca su una fissazione visibile.');let q=proj(Hinv(),fx.x,fx.y),pt=P.find(x=>x.key==$('calibrationPointSelect').value);if(!q)return setStatus('warn','Angoli mancanti','Segna prima i quattro angoli.');S.pairs[pt.key]={pt,obs:q,fx};S.mode='nav';render();}}
function nearFix(p){let best=null,d=1e9;S.fix.filter(x=>!isFinite(S.taskStart)||x.t<S.taskStart).forEach(f=>{let z=Math.hypot(f.x-p.x,f.y-p.y);if(z<d&&z<90){d=z;best=f}});return best}function mode(){$('interactionModeLabel').textContent=S.mode=='corner'?'segna angolo':S.mode=='cal'?'clicca fissazione':'navigazione'}
function H(){return hom([[0,0],[1,0],[1,1],[0,1]],['tl','tr','br','bl'].map(k=>S.corners[k]).filter(Boolean).map(p=>[p.x,p.y]))}function Hinv(){let h=H();return h&&inv(h)}
function spatial(){let hi=Hinv();if(!hi)return;let set=p=>{let q=proj(hi,p.x,p.y);if(S.model&&q)q=aff(S.model,q);p.s=q;p.nx=q?(q.x-.5)*2:NaN;p.dx=q?deg(q).x:NaN};S.gaze.forEach(set);S.fix.forEach(set);vel(S.gaze,'nx','nv');vel(S.gaze,'dx','dv');}
function fitCal(){let a=Object.values(S.pairs);if(a.length<4)return setStatus('warn','Calibrazione incompleta','Servono almeno 4 punti.');S.model=fit(a.map(x=>x.obs),a.map(x=>({x:x.pt.x,y:x.pt.y})));spatial();render();setStatus('ready','Calibrazione applicata','Correzione affine calcolata sui punti selezionati.')}
async function detect(){let v=$('sceneVideo');if(!Hinv()||!v.duration)return setStatus('warn','Preparazione incompleta','Carica video e segna angoli.');let old=v.currentTime,step=num($('detectionStepSec').value)||.05,thr=num($('targetThreshold').value)||210,cv=document.createElement('canvas'),cx=cv.getContext('2d',{willReadFrequently:true});cv.width=v.videoWidth;cv.height=v.videoHeight;S.targets=[];for(let t=isFinite(S.taskStart)?S.taskStart:0;t<v.duration;t+=step){await seek(t);cx.drawImage(v,0,0,cv.width,cv.height);let p=white(cx,cv.width,cv.height,thr);if(p){let q=proj(Hinv(),p.x,p.y);if(q&&q.x>=-.05&&q.x<=1.05&&q.y>=-.05&&q.y<=1.05){if(S.model)q=aff(S.model,q);let d=deg(q);S.targets.push({t,x:p.x,y:p.y,s:q,nx:(q.x-.5)*2,dx:d.x})}}$('detectionProgress').value=t/v.duration}vel(S.targets,'nx','nv');vel(S.targets,'dx','dv');S.trials=segment(S.targets);analyze();await seek(old);setStatus('ready','Target rilevato',`${S.targets.length} punti target, ${S.trials.length} trial.`);render()}
function seek(t){return new Promise(res=>{let v=$('sceneVideo'),done=()=>{v.removeEventListener('seeked',done);res()};v.addEventListener('seeked',done,{once:true});v.currentTime=t;setTimeout(done,300)})}function white(ctx,w,h,thr){let im=ctx.getImageData(0,0,w,h).data,xs=Object.values(S.corners).map(p=>p.x),ys=Object.values(S.corners).map(p=>p.y),x0=Math.max(0,Math.min(...xs)|0),x1=Math.min(w-1,Math.max(...xs)|0),y0=Math.max(0,Math.min(...ys)|0),y1=Math.min(h-1,Math.max(...ys)|0),sx=0,sy=0,n=0,hi=Hinv();for(let y=y0;y<=y1;y+=3)for(let x=x0;x<=x1;x+=3){let q=proj(hi,x,y);if(!q||q.x<0||q.x>1||q.y<0||q.y>1)continue;let i=(y*w+x)*4,r=im[i],g=im[i+1],b=im[i+2];if(r>thr&&g>thr&&b>thr){sx+=x;sy+=y;n++}}return n>2?{x:sx/n,y:sy/n}:null}
function segment(tg){let out=[],i=1;while(i<tg.length){while(i<tg.length&&Math.abs(tg[i].nx)<.18)i++;let st=i,sg=Math.sign(tg[i]?.nx||0);while(i<tg.length-1&&tg[i+1].t-tg[i].t<.35&&Math.sign(tg[i+1].nx||sg)==sg)i++;let seg=tg.slice(st,i+1),mx=Math.max(...seg.map(p=>Math.abs(p.nx)));if(seg.length>2&&mx>.25)out.push({onset:seg[0].t,end:seg.at(-1).t,direction:sg>0?'right':'left',amp:mx>.72?'wide':'short'});i++}return out}
function analyze(){let es=num($('earlyStartMs').value)/1000,ee=num($('earlyEndMs').value)/1000;S.results=S.trials.map((tr,i)=>{let sg=tr.direction=='right'?1:-1,a=tr.onset+es,b=tr.onset+ee,ge=S.gaze.filter(x=>x.t>=a&&x.t<=b&&!x.bad),te=S.targets.filter(x=>x.t>=a&&x.t<=b),gv=med(ge.map(x=>sg*x.nv)),tv=med(te.map(x=>sg*x.nv)),gd=med(ge.map(x=>sg*x.dv)),td=med(te.map(x=>sg*x.dv)),tot=S.gaze.filter(x=>x.t>=a&&x.t<=b).length;return{idx:i+1,...tr,drive:gv/tv,driveDeg:gd/td,valid:ge.length,total:tot,q:ge.length<5||!isFinite(gv/tv)?'bad':ge.length/tot<.6?'warn':'good'}});render()}
function render(){mode();$('sampleCount').textContent=S.gaze.length;$('fixationCount').textContent=S.fix.length;$('saccadeCount').textContent=S.sac.length;$('blinkCount').textContent=S.blink.length;$('trialCount').textContent=S.trials.length;$('calibrationStatus').textContent=Object.keys(S.pairs).length+'/9';draw();plots();tables();report()}
function draw(){let c=$('overlayCanvas'),r=c.getBoundingClientRect(),k=devicePixelRatio||1;c.width=r.width*k;c.height=r.height*k;let x=c.getContext('2d');x.setTransform(k,0,0,k,0,0);x.clearRect(0,0,r.width,r.height);Object.values(S.corners).forEach(p=>mark(x,toCan(p),'#ffd166',''));if(['tl','tr','br','bl'].every(k=>S.corners[k])){x.strokeStyle='white';x.beginPath();['tl','tr','br','bl'].forEach((k,i)=>{let p=toCan(S.corners[k]);i?x.lineTo(p.x,p.y):x.moveTo(p.x,p.y)});x.closePath();x.stroke()}let t=recTime();if($('showFixations').checked)S.fix.filter(f=>Math.abs(f.t-t)<2).forEach(f=>mark(x,toCan(f),'#ff9f43',''));let g=nearTime(S.gaze,t);if(g&&!g.bad)mark(x,toCan(g),'#4aa3ff','G');let ta=nearTime(S.targets,t);if(ta&&$('showTarget').checked)mark(x,toCan(ta),'#fff176','T');time()}
function mark(ctx,p,col,l){ctx.strokeStyle=col;ctx.fillStyle=col;ctx.beginPath();ctx.arc(p.x,p.y,7,0,7);ctx.stroke();ctx.beginPath();ctx.arc(p.x,p.y,2,0,7);ctx.fill();if(l){ctx.fillStyle='white';ctx.fillText(l,p.x,p.y-10)}}function plots(){plot($('normPlot'),'nx');plot($('degPlot'),'dx')}function plot(c,key){let ctx=c.getContext('2d'),w=c.width,h=c.height;ctx.clearRect(0,0,w,h);ctx.fillStyle='#fbfdfe';ctx.fillRect(0,0,w,h);let vals=[...S.gaze.map(x=>x[key]),...S.targets.map(x=>x[key])].filter(isFinite);if(!vals.length)return;let t0=Math.min(...S.gaze.map(x=>x.t)),t1=Math.max(...S.gaze.map(x=>x.t)),y0=Math.min(-1,...vals),y1=Math.max(1,...vals),X=t=>50+(t-t0)/(t1-t0)*(w-70),Y=v=>15+(1-(v-y0)/(y1-y0))*(h-40);line(ctx,S.gaze.filter(x=>!x.bad),key,X,Y,'#1d5f99');line(ctx,S.targets,key,X,Y,'#f0a500')}function line(ctx,a,k,X,Y,col){ctx.strokeStyle=col;ctx.beginPath();let s=0;a.forEach(p=>{if(!isFinite(p[k]))return;s?ctx.lineTo(X(p.t),Y(p[k])):(ctx.moveTo(X(p.t),Y(p[k])),s=1)});ctx.stroke()}
function tables(){let b=q=>`<span class="badge ${q}">${q=='good'?'OK':q=='warn'?'Controlla':'Scarsa'}</span>`;$('trialBody').innerHTML=S.results.length?S.results.map(r=>`<tr><td>${r.idx}</td><td>${f(r.onset,3)}</td><td>${r.direction=='right'?'Destra':'Sinistra'}</td><td>${r.amp=='wide'?'Ampia':'Breve'}</td><td>${f(r.drive,2)}</td><td>${f(r.driveDeg,2)}</td><td>-</td><td>-</td><td>${r.valid}/${r.total}</td><td>${b(r.q)}</td></tr>`).join(''):'<tr><td colspan="10" class="empty">Nessun trial rilevato.</td></tr>'}
function report(){let r=S.results.filter(x=>x.q!='bad'),R=med(r.filter(x=>x.direction=='right').map(x=>x.drive)),L=med(r.filter(x=>x.direction=='left').map(x=>x.drive)),A=(R-L)/(R+L);$('reportSummary').innerHTML=isFinite(A)?`<div class="report-card">Indice asimmetria controllato per ampiezza: <strong>${f(A,3)}</strong><p class="hint">positivo = maggiore drive verso destra; negativo = maggiore drive verso sinistra.</p></div><div class="report-card">Drive destra ${f(R,2)} | sinistra ${f(L,2)}</div>`:'Esegui rilevamento e analisi per generare il report.'}
function recTime(){return($('sceneVideo').currentTime||0)+num($('syncOffsetMs').value)/1000}function time(){$('videoTimeLabel').textContent=f($('sceneVideo').currentTime,3)+' s';$('gazeTimeLabel').textContent=f(recTime(),3)+' s'}function loop(){draw();S.raf=requestAnimationFrame(loop)}function nearTime(a,t){return a.reduce((p,c)=>!p||Math.abs(c.t-t)<Math.abs(p.t-t)?c:p,null)}
function deg(p){let w=num($('monitorWidthCm').value),h=num($('monitorHeightCm').value),d=num($('viewingDistanceCm').value);return isFinite(w)&&isFinite(h)&&isFinite(d)&&w>0&&h>0&&d>0?{x:Math.atan2((p.x-.5)*w,d)*180/Math.PI,y:Math.atan2((.5-p.y)*h,d)*180/Math.PI}:{x:NaN,y:NaN}}function vel(a,k,o){for(let i=1;i<a.length-1;i++){let dt=a[i+1].t-a[i-1].t;a[i][o]=dt>0?(a[i+1][k]-a[i-1][k])/dt:NaN}}function med(a){a=a.filter(isFinite).sort((x,y)=>x-y);return a.length?a.length%2?a[a.length>>1]:(a[a.length/2-1]+a[a.length/2])/2:NaN}function f(x,d=2){return isFinite(x)?x.toLocaleString('it-IT',{maximumFractionDigits:d,minimumFractionDigits:d}):'-'}function setStatus(k,t,m){$('statusBand').className='status-band '+k;$('statusTitle').textContent=t;$('statusText').textContent=m}
function hom(src,dst){if(dst.length<4)return null;let A=[],b=[];for(let i=0;i<4;i++){let[x,y]=src[i],[u,v]=dst[i];A.push([x,y,1,0,0,0,-u*x,-u*y]);b.push(u);A.push([0,0,0,x,y,1,-v*x,-v*y]);b.push(v)}let h=solve(A,b);return h&&[h[0],h[1],h[2],h[3],h[4],h[5],h[6],h[7],1]}function inv(H){let[a,b,c,d,e,f,g,h,i]=H,A=e*i-f*h,B=c*h-b*i,C=b*f-c*e,D=f*g-d*i,E=a*i-c*g,F=c*d-a*f,G=d*h-e*g,J=a*e-b*d,det=a*A+b*D+c*G;return Math.abs(det)<1e-12?null:[A/det,B/det,C/det,D/det,E/det,F/det,G/det,(c*g-a*h)/det,J/det]}function proj(H,x,y){if(!H)return null;let w=H[6]*x+H[7]*y+H[8];return{x:(H[0]*x+H[1]*y+H[2])/w,y:(H[3]*x+H[4]*y+H[5])/w}}function fit(s,d){let ax=[0,0,0],ay=[0,0,0];let sx=med(d.map(p=>p.x))-med(s.map(p=>p.x)),sy=med(d.map(p=>p.y))-med(s.map(p=>p.y));return{sx,sy}}function aff(m,p){return{x:p.x+m.sx,y:p.y+m.sy}}function solve(A,b){let n=b.length;for(let c=0;c<n;c++){let p=c;for(let r=c+1;r<n;r++)if(Math.abs(A[r][c])>Math.abs(A[p][c]))p=r;if(Math.abs(A[p][c])<1e-12)return null;[A[c],A[p]]=[A[p],A[c]];[b[c],b[p]]=[b[p],b[c]];let v=A[c][c];for(let j=c;j<n;j++)A[c][j]/=v;b[c]/=v;for(let r=0;r<n;r++){if(r==c)continue;let f=A[r][c];for(let j=c;j<n;j++)A[r][j]-=f*A[c][j];b[r]-=f*b[c]}}return b}
init();
