const SUPABASE_URL='https://kujyowhezihjambhpahe.supabase.co';
const SUPABASE_KEY='sb_publishable_VBzZaA3NAIvqMxJcZZTwPg_4_GEi1a3';
const db=window.supabase?window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY):null;
const K='activityTimerState.v14';
const C=['#2563eb','#7c3aed','#0f766e','#059669','#f59e0b','#ef4444','#0891b2','#db2777','#4f46e5','#65a30d','#c026d3'];
const id=()=>crypto.randomUUID(),today=()=>new Date().toISOString().slice(0,10),q=x=>document.querySelector(x);
const base=()=>[{name:'Clinica pazienti',targetMinutes:240},{name:'Ricerca',targetMinutes:120},{name:'Didattica',targetMinutes:60},{name:'Casa',targetMinutes:30},{name:'Relazioni sociali',targetMinutes:30},{name:'Alimentazione',targetMinutes:60},{name:'Allenamento',targetMinutes:45},{name:'Tempo libero',targetMinutes:60}].map((a,i)=>({id:id(),name:a.name,targetMinutes:a.targetMinutes,color:C[i],seconds:0}));
const def=()=>({date:today(),period:'week',budgetMinutes:660,activeId:null,isPaused:false,lastTickAt:null,activities:base(),logs:{},alerts:{}});
let s=load(),user=null,cloudReady=false,saveTimer=null,forceCloudTimer=null,audioCtx=null,alarmTimer=null;
const ed=q('#activityEditor'),bs=q('#activityButtons'),tpl=q('#activityRowTemplate'),ttl=q('#timerTitle'),el=q('#elapsedTime'),info=q('#targetInfo'),pause=q('#pauseBtn'),stop=q('#stopBtn'),add=q('#addActivityBtn'),reset=q('#resetDayBtn'),total=q('#totalTimeLabel'),summary=q('#targetSummary'),globalPct=q('#globalPercent'),budgetInput=q('#budgetInput'),periodLabel=q('#periodLabel'),controls=q('#periodControls'),leg=q('#legend'),cv=q('#pieChart'),ctx=cv.getContext('2d'),cloud=q('#cloudStatus'),authBox=q('#authBox'),email=q('#emailInput'),pwd=q('#passwordInput'),signIn=q('#signInBtn'),signUp=q('#signUpBtn'),signOut=q('#signOutBtn');
function load(){for(const k of [K,'activityTimerState.v13','activityTimerState.v12','activityTimerState.v11','activityTimerState.v10','activityTimerState.v9','activityTimerState.v8','activityTimerState.v7','activityTimerState.v6','activityTimerState.v5','activityTimerState.v4']){try{let x=JSON.parse(localStorage.getItem(k));if(x&&x.activities){let y={...def(),...x,budgetMinutes:+x.budgetMinutes||660,alerts:x.alerts||{}};if(y.date!==today()){y.activeId=null;y.isPaused=false;y.lastTickAt=null;y.alerts={}}return y}}catch{}}return def()}
function setCloud(t){cloud.textContent=t}
function setBusy(v){signIn.disabled=signUp.disabled=signOut.disabled=!!v}
function timeout(p,ms,msg){return Promise.race([p,new Promise((_,r)=>setTimeout(()=>r(Error(msg||'Tempo scaduto')),ms))])}
function active(){return s.activities.find(a=>a.id===s.activeId)}
function running(){return !!(s.activeId&&!s.isPaused&&s.lastTickAt)}
function syncLog(){let d=today();s.logs=s.logs||{};s.logs[d]=s.logs[d]||{};s.activities.forEach(a=>s.logs[d][a.id]=a.seconds||0)}
function save(){syncLog();localStorage.setItem(K,JSON.stringify(s));queueCloudSave(false)}
function queueCloudSave(fast=false){if(!user||!cloudReady)return;clearTimeout(saveTimer);saveTimer=setTimeout(saveCloud,fast?60:650)}
async function saveCloud(){if(!user)return;try{syncLog();setCloud('Salvataggio cloud...');let acts=s.activities.map((a,i)=>({user_id:user.id,id:a.id,name:a.name,target_minutes:+a.targetMinutes||0,color:a.color,sort_order:i,updated_at:new Date().toISOString()}));let logs=[];Object.entries(s.logs||{}).forEach(([date,row])=>Object.entries(row||{}).forEach(([activity_id,seconds])=>logs.push({user_id:user.id,id:`${activity_id}_${date}`,activity_id,date,seconds:Math.max(0,Math.round(seconds||0)),updated_at:new Date().toISOString()})));let current={user_id:user.id,activity_id:s.activeId,started_at:running()?new Date(s.lastTickAt).toISOString():null,is_paused:!!s.isPaused,pause_elapsed_seconds:0,updated_at:new Date().toISOString()};let e0=(await timeout(db.from('activity_timer_settings').upsert({user_id:user.id,budget_minutes:budget(),updated_at:new Date().toISOString()},{onConflict:'user_id'}),12000,'Timeout salvataggio impostazioni')).error;let eC=(await timeout(db.from('activity_timer_current').upsert(current,{onConflict:'user_id'}),12000,'Timeout salvataggio timer attivo')).error;let e1=null,e2=null;if(acts.length)e1=(await timeout(db.from('activity_timer_activities').upsert(acts,{onConflict:'user_id,id'}),12000,'Timeout salvataggio attività')).error;if(logs.length)e2=(await timeout(db.from('activity_timer_logs').upsert(logs,{onConflict:'user_id,activity_id,date'}),12000,'Timeout salvataggio log')).error;setCloud(e0||eC||e1||e2?`Errore cloud: ${(e0||eC||e1||e2).message}`:`Salvato su Supabase · ${new Date().toLocaleTimeString('it-IT',{hour:'2-digit',minute:'2-digit'})}`)}catch(err){setCloud(`Errore cloud: ${err.message}`)}}
async function forceSaveCloud(){if(!user||!cloudReady)return;clearTimeout(saveTimer);await saveCloud()}
async function loadCloud(){if(!user)return;try{setCloud('Caricamento dati Supabase...');let localRun={activeId:s.activeId,isPaused:s.isPaused,lastTickAt:s.lastTickAt,date:s.date};let r0=await timeout(db.from('activity_timer_settings').select('*').maybeSingle(),12000,'Timeout caricamento impostazioni');let r1=await timeout(db.from('activity_timer_activities').select('*').order('sort_order',{ascending:true}),12000,'Timeout caricamento attività');let r2=await timeout(db.from('activity_timer_logs').select('*'),12000,'Timeout caricamento log');let r3=await timeout(db.from('activity_timer_current').select('*').maybeSingle(),12000,'Timeout caricamento timer attivo');let acts=r1.data,logs=r2.data,current=r3.data,e0=r0.error,e1=r1.error,e2=r2.error,e3=r3.error;if(e0||e1||e2||e3){setCloud(`Errore caricamento cloud: ${(e0||e1||e2||e3).message}`);return}if(r0.data&&r0.data.budget_minutes)s.budgetMinutes=Number(r0.data.budget_minutes)||660;if(acts&&acts.length){let todayLogs=Object.fromEntries((logs||[]).filter(x=>x.date===today()).map(x=>[x.activity_id,x.seconds||0]));s.activities=acts.map(a=>({id:a.id,name:a.name,targetMinutes:Number(a.target_minutes)||0,color:a.color||C[0],seconds:todayLogs[a.id]||0}));s.logs={};(logs||[]).forEach(l=>{s.logs[l.date]=s.logs[l.date]||{};s.logs[l.date][l.activity_id]=l.seconds||0});s.date=today();restoreRunning(current,localRun);accrue();localStorage.setItem(K,JSON.stringify(s));cloudReady=true;setCloud(`Accesso confermato: dati caricati da Supabase (${user.email}).`)}else{cloudReady=true;await saveCloud();setCloud(`Accesso confermato: primo salvataggio creato su Supabase (${user.email}).`)}renderAll()}catch(err){setCloud(`Errore caricamento cloud: ${err.message}`)}}
function restoreRunning(current,localRun){s.activeId=null;s.isPaused=false;s.lastTickAt=null;if(current&&current.activity_id&&s.activities.some(a=>a.id===current.activity_id)){let t=current.started_at?Date.parse(current.started_at):null;if(current.is_paused){s.activeId=current.activity_id;s.isPaused=true;s.lastTickAt=null;return}if(t&&Number.isFinite(t)&&dateStr(new Date(t))===today()){s.activeId=current.activity_id;s.isPaused=false;s.lastTickAt=t;return}}if(localRun&&localRun.date===today()&&localRun.activeId&&s.activities.some(a=>a.id===localRun.activeId)){s.activeId=localRun.activeId;s.isPaused=!!localRun.isPaused;s.lastTickAt=localRun.isPaused?null:(localRun.lastTickAt||Date.now())}}
function esc(v){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function fmt(n){n=Math.max(0,Math.floor(n));let h=Math.floor(n/3600),m=Math.floor(n%3600/60),x=n%60;return h?`${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(x).padStart(2,'0')}`:`${String(m).padStart(2,'0')}:${String(x).padStart(2,'0')}`}
function fmtHM(min){min=Math.max(0,Math.round(min||0));let h=Math.floor(min/60),m=min%60;return h&&m?`${h} h ${m} min`:h?`${h} h`:`${m} min`}
function targetTotal(){return s.activities.reduce((p,a)=>p+(+a.targetMinutes||0),0)}
function budget(){return Math.max(1,Math.round(+s.budgetMinutes||660))}
function pctNum(min){return (Math.max(0,+min||0)/budget())*100}
function targetPct(a){let p=pctNum(a.targetMinutes);return `${p>=10?Math.round(p):p.toFixed(1)}%`}
function targetProgress(a){let total=(+a.targetMinutes||0)*60;return total?Math.min(100,(Math.max(0,+a.seconds||0)/total)*100):0}
function targetProgressFull(a){let total=(+a.targetMinutes||0)*60;return total?(Math.max(0,+a.seconds||0)/total)*100:0}
function targetProgressLabel(a){let p=targetProgressFull(a);return `${p>=10?Math.round(p):p.toFixed(1)}% obiettivo`}
function totalPct(){return pctNum(targetTotal())}
function dateStr(d){return d.toISOString().slice(0,10)}
function datesFor(p){let now=new Date(),out=[];if(p==='day')return [today()];if(p==='week'){let d=new Date(now);let day=(d.getDay()+6)%7;d.setDate(d.getDate()-day);for(let i=0;i<7;i++){let x=new Date(d);x.setDate(d.getDate()+i);out.push(dateStr(x))}}else{let y=now.getFullYear(),m=now.getMonth(),last=new Date(y,m+1,0).getDate();for(let i=1;i<=last;i++)out.push(dateStr(new Date(y,m,i)))}return out}
function periodName(){return s.period==='day'?'oggi':s.period==='week'?'questa settimana':'questo mese'}
function checkDay(){if(s.date!==today()){syncLog();s.activities=s.activities.map(a=>({...a,seconds:(s.logs?.[today()]?.[a.id])||0}));s.activeId=null;s.isPaused=false;s.lastTickAt=null;s.date=today();s.alerts={};save();return true}return false}
function alarmKey(a){return `${today()}_${a.id}_95`}
function unlockAlarm(){try{let AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;if(!audioCtx)audioCtx=new AC();if(audioCtx.state==='suspended')audioCtx.resume()}catch{}}
async function requestNotifications(){try{if('Notification' in window&&Notification.permission==='default')await Notification.requestPermission()}catch{}}
function prepareAlarm(){unlockAlarm();requestNotifications()}
function playAlarm(){try{unlockAlarm();if(!audioCtx)return;let n=audioCtx.currentTime;[0,.34,.68,1.16,1.5].forEach((off,i)=>{let o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=i%2?'triangle':'sine';o.frequency.setValueAtTime(i%2?880:660,n+off);g.gain.setValueAtTime(.001,n+off);g.gain.linearRampToValueAtTime(.36,n+off+.035);g.gain.exponentialRampToValueAtTime(.001,n+off+.27);o.connect(g);g.connect(audioCtx.destination);o.start(n+off);o.stop(n+off+.29)})}catch{}}
function notifyAlarm(a){try{if(navigator.vibrate)navigator.vibrate([450,180,450,180,700]);if('Notification' in window&&Notification.permission==='granted')new Notification('Timer Attività',{body:`${a.name} ha raggiunto il 95% dell'obiettivo giornaliero.`,tag:`timer-95-${a.id}-${today()}`,renotify:true})}catch{}}
function triggerAlarm(a){s.alerts=s.alerts||{};s.alerts[alarmKey(a)]=true;save();playAlarm();notifyAlarm(a);setCloud(`Avviso: ${a.name} ha raggiunto il 95% dell'obiettivo.`)}
function checkAlarm(a=active()){if(!a)return;let key=alarmKey(a);if(targetProgressFull(a)>=95&&!(s.alerts&&s.alerts[key]))triggerAlarm(a)}
function scheduleAlarm(){clearTimeout(alarmTimer);let a=active();if(!a||s.isPaused)return;let target=(+a.targetMinutes||0)*60*.95,remaining=Math.ceil(target-(+a.seconds||0));if(remaining<=0){checkAlarm(a);return}alarmTimer=setTimeout(()=>{accrue();checkAlarm(a);renderAll()},Math.min(remaining*1000,2147483647))}
function accrue(){checkDay();let a=active();if(!a||s.isPaused)return false;let n=Date.now();if(!s.lastTickAt){s.lastTickAt=n;save();scheduleAlarm();return false}let d=Math.floor((n-s.lastTickAt)/1000);if(d>0){a.seconds+=d;s.lastTickAt+=d*1000;save();checkAlarm(a);scheduleAlarm();return true}return false}
function periodTotals(){syncLog();let ds=datesFor(s.period),map={};s.activities.forEach(a=>map[a.id]=0);ds.forEach(d=>{let row=s.logs?.[d]||{};s.activities.forEach(a=>map[a.id]+=row[a.id]||0)});return map}
function renderSummary(){let m=targetTotal(),b=budget(),p=totalPct();if(document.activeElement!==budgetInput)budgetInput.value=b;summary.textContent=`Totale obiettivi giornalieri: ${fmtHM(m)} (${m} min) su un budget di ${fmtHM(b)} (${b} min). Su 5 giorni lavorativi: ${fmtHM(m*5)}.`;globalPct.textContent=`Totale percentuale: ${p.toFixed(1)}%${p>100?' · oltre il budget':''}`;globalPct.className=`global-percent ${p>100?'warn':'ok'}`}
function updateEditorPcts(){[...ed.children].forEach((r,i)=>{let p=r.querySelector('.activity-percent');if(p&&s.activities[i])p.textContent=targetPct(s.activities[i])})}
function refreshAfterEdit(){renderSummary();updateEditorPcts();renderButtons();renderTimer();renderChart()}
function renderEditor(){ed.innerHTML='';s.activities.forEach(a=>{let r=tpl.content.firstElementChild.cloneNode(true),n=r.querySelector('.activity-name'),t=r.querySelector('.activity-target'),pct=r.querySelector('.activity-percent'),rm=r.querySelector('.remove-activity');n.value=a.name;t.value=a.targetMinutes;pct.textContent=targetPct(a);n.oninput=()=>{a.name=n.value.trim()||'Senza nome';save();renderButtons();renderTimer();renderChart()};t.oninput=()=>{a.targetMinutes=Math.max(1,+t.value||1);save();refreshAfterEdit();scheduleAlarm()};rm.onclick=()=>{if(s.activities.length<2)return;if(s.activeId===a.id)stopTimer();s.activities=s.activities.filter(x=>x.id!==a.id);save();renderAll()};ed.appendChild(r)})}
function renderButtons(){bs.innerHTML='';s.activities.forEach(a=>{let b=document.createElement('button');let done=Math.round(a.seconds/60),p=targetProgress(a);b.type='button';b.className='big-activity-btn';b.style.background=a.color;b.style.setProperty('--progress',`${p}%`);b.classList.toggle('active',a.id===s.activeId&&!s.isPaused);b.classList.toggle('complete',p>=100);b.innerHTML=`<span class="activity-progress-fill" aria-hidden="true"></span><span class="activity-btn-content"><span class="activity-btn-title">${esc(a.name)}</span><span class="activity-btn-meta">${done} / ${a.targetMinutes} min oggi · ${targetProgressLabel(a)}</span></span>`;b.onclick=()=>start(a.id);bs.appendChild(b)})}
function renderTimer(){let a=active();pause.disabled=stop.disabled=!a;if(!a){ttl.textContent='Nessuna attività';el.textContent='00:00';info.textContent='Premi un pulsante per iniziare.';pause.textContent='Pausa';return}ttl.textContent=a.name;el.textContent=fmt(a.seconds);let rem=Math.max(0,a.targetMinutes*60-a.seconds);info.textContent=`${s.isPaused?'In pausa':'In corso'} · obiettivo ${a.targetMinutes} min (${targetPct(a)} del budget) · ${targetProgressLabel(a)} · restano ${fmt(rem)}`;pause.textContent=s.isPaused?'Riprendi':'Pausa'}
function renderPeriodButtons(){[...controls.querySelectorAll('button')].forEach(b=>{b.style.opacity=b.dataset.period===s.period?'1':'.55';b.onclick=()=>{s.period=b.dataset.period;save();renderChart();renderPeriodButtons()}})}
function renderChart(){let totals=periodTotals(),sum=Object.values(totals).reduce((p,x)=>p+x,0);total.textContent=`Totale registrato ${periodName()}: ${fmtHM(Math.round(sum/60))}`;periodLabel.textContent=`Vista ${s.period==='day'?'giornaliera':s.period==='week'?'settimanale':'mensile'} · confronto tra le aree`;ctx.clearRect(0,0,cv.width,cv.height);let c=cv.width/2,r=cv.width*.38;if(!sum){ctx.beginPath();ctx.arc(c,c,r,0,Math.PI*2);ctx.fillStyle='#e2e8f0';ctx.fill();ctx.beginPath();ctx.arc(c,c,r*.52,0,Math.PI*2);ctx.fillStyle='white';ctx.fill();ctx.fillStyle='#64748b';ctx.font='800 26px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('0m',c,c);leg.innerHTML='<p class="target-info">Registra tempo per vedere la distribuzione.</p>';return}let st=-Math.PI/2;leg.innerHTML='';s.activities.forEach(a=>{let sec=totals[a.id]||0;if(sec<=0)return;let sl=sec/sum,en=st+sl*Math.PI*2;ctx.beginPath();ctx.moveTo(c,c);ctx.arc(c,c,r,st,en);ctx.closePath();ctx.fillStyle=a.color;ctx.fill();let p=Math.round(sl*100),it=document.createElement('div');it.className='legend-item';it.innerHTML=`<span class="legend-dot" style="background:${a.color}"></span><strong>${esc(a.name)}</strong><span>${p}% · ${fmtHM(Math.round(sec/60))}</span>`;leg.appendChild(it);st=en});ctx.beginPath();ctx.arc(c,c,r*.52,0,Math.PI*2);ctx.fillStyle='white';ctx.fill();ctx.fillStyle='#111827';ctx.font='900 30px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(fmtHM(Math.round(sum/60)),c,c)}
function start(x){prepareAlarm();accrue();s.activeId=x;s.isPaused=false;s.lastTickAt=Date.now();save();queueCloudSave(true);renderAll();scheduleAlarm()}
function pauseTimer(){let a=active();if(!a)return;if(!s.isPaused)accrue();s.isPaused=!s.isPaused;s.lastTickAt=s.isPaused?null:Date.now();save();queueCloudSave(true);renderAll();scheduleAlarm()}
function stopTimer(){clearTimeout(alarmTimer);accrue();s.activeId=null;s.isPaused=false;s.lastTickAt=null;save();queueCloudSave(true);renderAll()}
function tick(){if(accrue()){renderButtons();renderTimer();renderChart()}}
function addAct(){let i=s.activities.length;s.activities.push({id:id(),name:`Attività ${i+1}`,targetMinutes:25,color:C[i%C.length],seconds:0});save();renderAll()}
function resetDay(){if(!confirm('Vuoi azzerare il tempo registrato oggi?'))return;s.activities=s.activities.map(a=>({...a,seconds:0}));s.alerts={};syncLog();s.logs[today()]={};stopTimer()}
function renderAll(){renderSummary();renderEditor();renderButtons();renderTimer();renderPeriodButtons();renderChart()}
async function initAuth(){try{if(!db){setCloud('Supabase non caricato: uso solo salvataggio locale.');authBox.style.display='none';return}setCloud('Controllo accesso Supabase...');let {data}=await timeout(db.auth.getSession(),8000,'Supabase non risponde. Controlla connessione o ricarica la pagina.');user=data.session?.user||null;updateAuthUi();if(user)await loadCloud();db.auth.onAuthStateChange(async(_,session)=>{user=session?.user||null;updateAuthUi();if(user)await loadCloud()})}catch(err){cloudReady=false;setCloud(`Non connesso: ${err.message}`);updateAuthUi()}}
function updateAuthUi(){signOut.style.display=user?'inline-block':'none';signIn.style.display=user?'none':'inline-block';signUp.style.display=user?'none':'inline-block';email.style.display=user?'none':'block';pwd.style.display=user?'none':'block';setBusy(false);if(user){cloudReady=true;if(!cloud.textContent.includes('Accesso confermato'))setCloud(`Connesso a Supabase come ${user.email}.`)}else{cloudReady=false;if(cloud.textContent==='Controllo accesso...'||cloud.textContent==='Controllo accesso Supabase...')setCloud('Non connesso: i dati restano salvati solo su questo dispositivo.')}}
signIn.onclick=async()=>{try{if(!db)return setCloud('Supabase non caricato. Ricarica la pagina.');if(!email.value.trim()||!pwd.value)return setCloud('Inserisci email e password.');setBusy(true);setCloud('Accesso in corso...');let {data,error}=await timeout(db.auth.signInWithPassword({email:email.value.trim(),password:pwd.value}),12000,'Timeout accesso Supabase. Riprova.');if(error){user=null;updateAuthUi();return setCloud(`Accesso non riuscito: ${error.message}`)}user=data.user;updateAuthUi();setCloud(`Accesso riuscito come ${user.email}. Carico i dati...`);await loadCloud()}catch(err){user=null;updateAuthUi();setCloud(`Accesso non riuscito: ${err.message}`)}};
signUp.onclick=async()=>{try{if(!db)return setCloud('Supabase non caricato. Ricarica la pagina.');if(!email.value.trim()||!pwd.value)return setCloud('Inserisci email e password.');setBusy(true);setCloud('Creazione account in corso...');let {data,error}=await timeout(db.auth.signUp({email:email.value.trim(),password:pwd.value}),12000,'Timeout creazione account. Riprova.');if(error){updateAuthUi();return setCloud(`Registrazione non riuscita: ${error.message}`)}user=data.user||null;updateAuthUi();setCloud(user?`Account creato/accesso attivo come ${user.email}.`:'Account creato. Controlla eventuale email di conferma, poi premi Accedi.');if(user)await loadCloud()}catch(err){updateAuthUi();setCloud(`Registrazione non riuscita: ${err.message}`)}};
signOut.onclick=async()=>{try{setBusy(true);setCloud('Uscita in corso...');await timeout(db.auth.signOut(),8000,'Timeout uscita. Ricarica la pagina.');user=null;updateAuthUi();setCloud('Disconnesso da Supabase. I dati restano disponibili in locale.')}catch(err){setCloud(`Errore uscita: ${err.message}`);setBusy(false)}};
budgetInput.oninput=()=>{s.budgetMinutes=Math.max(1,+budgetInput.value||1);save();refreshAfterEdit();scheduleAlarm()};
document.addEventListener('pointerdown',prepareAlarm,{once:true});
document.addEventListener('visibilitychange',()=>{if(document.hidden){accrue();save();forceSaveCloud()}else{accrue();checkAlarm();renderAll();scheduleAlarm()}});
window.addEventListener('pagehide',()=>{accrue();save();forceSaveCloud()});
window.addEventListener('pageshow',()=>{accrue();checkAlarm();renderAll();scheduleAlarm()});
forceCloudTimer=setInterval(()=>{if(running())forceSaveCloud()},30000);
pause.onclick=pauseTimer;stop.onclick=stopTimer;add.onclick=addAct;reset.onclick=resetDay;accrue();renderAll();initAuth();scheduleAlarm();setInterval(tick,1000);
