const K='activityTimerState.v6';
const C=['#2563eb','#7c3aed','#0f766e','#059669','#f59e0b','#ef4444','#0891b2','#db2777','#4f46e5','#65a30d','#c026d3'];
const id=()=>crypto.randomUUID(),today=()=>new Date().toISOString().slice(0,10),q=x=>document.querySelector(x);
const base=()=>[{name:'Clinica pazienti',targetMinutes:240},{name:'Ricerca',targetMinutes:120},{name:'Didattica',targetMinutes:60},{name:'Casa',targetMinutes:30},{name:'Relazioni sociali',targetMinutes:30},{name:'Alimentazione',targetMinutes:60},{name:'Allenamento',targetMinutes:45},{name:'Tempo libero',targetMinutes:60}].map((a,i)=>({id:id(),name:a.name,targetMinutes:a.targetMinutes,color:C[i],seconds:0}));
const def=()=>({date:today(),period:'week',activeId:null,isPaused:false,lastTickAt:null,activities:base(),logs:{}});
let s=load();
const ed=q('#activityEditor'),bs=q('#activityButtons'),tpl=q('#activityRowTemplate'),ttl=q('#timerTitle'),el=q('#elapsedTime'),info=q('#targetInfo'),pause=q('#pauseBtn'),stop=q('#stopBtn'),add=q('#addActivityBtn'),reset=q('#resetDayBtn'),total=q('#totalTimeLabel'),summary=q('#targetSummary'),periodLabel=q('#periodLabel'),controls=q('#periodControls'),leg=q('#legend'),cv=q('#pieChart'),ctx=cv.getContext('2d');
function load(){try{let x=JSON.parse(localStorage.getItem(K));return x&&x.activities?{...def(),...x,activeId:null,isPaused:false,lastTickAt:null}:def()}catch{return def()}}
function syncLog(){let d=today();s.logs=s.logs||{};s.logs[d]=s.logs[d]||{};s.activities.forEach(a=>s.logs[d][a.id]=a.seconds||0)}
function save(){syncLog();localStorage.setItem(K,JSON.stringify(s))}
function esc(v){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function fmt(n){n=Math.max(0,Math.floor(n));let h=Math.floor(n/3600),m=Math.floor(n%3600/60),x=n%60;return h?`${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(x).padStart(2,'0')}`:`${String(m).padStart(2,'0')}:${String(x).padStart(2,'0')}`}
function fmtHM(min){min=Math.max(0,Math.round(min||0));let h=Math.floor(min/60),m=min%60;return h&&m?`${h} h ${m} min`:h?`${h} h`:`${m} min`}
function targetTotal(){return s.activities.reduce((p,a)=>p+(+a.targetMinutes||0),0)}
function targetPct(a){let m=+a.targetMinutes||0,t=targetTotal();return t?`${Math.round((m/t)*100)}%`:'0%'}
function active(){return s.activities.find(a=>a.id===s.activeId)}
function dateStr(d){return d.toISOString().slice(0,10)}
function datesFor(p){let now=new Date(),out=[];if(p==='day')return [today()];if(p==='week'){let d=new Date(now);let day=(d.getDay()+6)%7;d.setDate(d.getDate()-day);for(let i=0;i<7;i++){let x=new Date(d);x.setDate(d.getDate()+i);out.push(dateStr(x))}}else{let y=now.getFullYear(),m=now.getMonth(),last=new Date(y,m+1,0).getDate();for(let i=1;i<=last;i++)out.push(dateStr(new Date(y,m,i)))}return out}
function periodName(){return s.period==='day'?'oggi':s.period==='week'?'questa settimana':'questo mese'}
function checkDay(){if(s.date!==today()){syncLog();s.activities=s.activities.map(a=>({...a,seconds:(s.logs?.[today()]?.[a.id])||0}));s.activeId=null;s.isPaused=false;s.lastTickAt=null;s.date=today();save()}}
function periodTotals(){syncLog();let ds=datesFor(s.period),map={};s.activities.forEach(a=>map[a.id]=0);ds.forEach(d=>{let row=s.logs?.[d]||{};s.activities.forEach(a=>map[a.id]+=row[a.id]||0)});return map}
function renderSummary(){let m=targetTotal();summary.textContent=`Totale obiettivi giornalieri: ${fmtHM(m)} (${m} min). Su 5 giorni lavorativi: ${fmtHM(m*5)}.`}
function renderEditor(){ed.innerHTML='';s.activities.forEach(a=>{let r=tpl.content.firstElementChild.cloneNode(true),n=r.querySelector('.activity-name'),t=r.querySelector('.activity-target'),pct=r.querySelector('.activity-percent'),rm=r.querySelector('.remove-activity');n.value=a.name;t.value=a.targetMinutes;pct.textContent=targetPct(a);n.oninput=()=>{a.name=n.value.trim()||'Senza nome';save();renderAll()};t.oninput=()=>{a.targetMinutes=Math.max(1,+t.value||1);save();renderAll()};rm.onclick=()=>{if(s.activities.length<2)return;if(s.activeId===a.id)stopTimer();s.activities=s.activities.filter(x=>x.id!==a.id);save();renderAll()};ed.appendChild(r)})}
function renderButtons(){bs.innerHTML='';s.activities.forEach(a=>{let b=document.createElement('button');b.type='button';b.className='big-activity-btn';b.style.background=a.color;b.classList.toggle('active',a.id===s.activeId&&!s.isPaused);b.innerHTML=`<span>${esc(a.name)}</span><span>${Math.round(a.seconds/60)} / ${a.targetMinutes} min oggi · ${targetPct(a)}</span>`;b.onclick=()=>start(a.id);bs.appendChild(b)})}
function renderTimer(){let a=active();pause.disabled=stop.disabled=!a;if(!a){ttl.textContent='Nessuna attività';el.textContent='00:00';info.textContent='Premi un pulsante per iniziare.';pause.textContent='Pausa';return}ttl.textContent=a.name;el.textContent=fmt(a.seconds);let rem=Math.max(0,a.targetMinutes*60-a.seconds);info.textContent=`${s.isPaused?'In pausa':'In corso'} · obiettivo ${a.targetMinutes} min (${targetPct(a)}) · restano ${fmt(rem)}`;pause.textContent=s.isPaused?'Riprendi':'Pausa'}
function renderPeriodButtons(){[...controls.querySelectorAll('button')].forEach(b=>{b.style.opacity=b.dataset.period===s.period?'1':'.55';b.onclick=()=>{s.period=b.dataset.period;save();renderChart();renderPeriodButtons()}})}
function renderChart(){let totals=periodTotals(),sum=Object.values(totals).reduce((p,x)=>p+x,0);total.textContent=`Totale registrato ${periodName()}: ${fmtHM(Math.round(sum/60))}`;periodLabel.textContent=`Vista ${s.period==='day'?'giornaliera':s.period==='week'?'settimanale':'mensile'} · confronto tra le aree`;ctx.clearRect(0,0,cv.width,cv.height);let c=cv.width/2,r=cv.width*.38;if(!sum){ctx.beginPath();ctx.arc(c,c,r,0,Math.PI*2);ctx.fillStyle='#e2e8f0';ctx.fill();ctx.beginPath();ctx.arc(c,c,r*.52,0,Math.PI*2);ctx.fillStyle='white';ctx.fill();ctx.fillStyle='#64748b';ctx.font='800 26px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('0m',c,c);leg.innerHTML='<p class="target-info">Registra tempo per vedere la distribuzione.</p>';return}let st=-Math.PI/2;leg.innerHTML='';s.activities.forEach(a=>{let sec=totals[a.id]||0;if(sec<=0)return;let sl=sec/sum,en=st+sl*Math.PI*2;ctx.beginPath();ctx.moveTo(c,c);ctx.arc(c,c,r,st,en);ctx.closePath();ctx.fillStyle=a.color;ctx.fill();let p=Math.round(sl*100),it=document.createElement('div');it.className='legend-item';it.innerHTML=`<span class="legend-dot" style="background:${a.color}"></span><strong>${esc(a.name)}</strong><span>${p}% · ${fmtHM(Math.round(sec/60))}</span>`;leg.appendChild(it);st=en});ctx.beginPath();ctx.arc(c,c,r*.52,0,Math.PI*2);ctx.fillStyle='white';ctx.fill();ctx.fillStyle='#111827';ctx.font='900 30px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(fmtHM(Math.round(sum/60)),c,c)}
function start(x){s.activeId=x;s.isPaused=false;s.lastTickAt=Date.now();save();renderAll()}
function pauseTimer(){let a=active();if(!a)return;s.isPaused=!s.isPaused;s.lastTickAt=s.isPaused?null:Date.now();save();renderAll()}
function stopTimer(){s.activeId=null;s.isPaused=false;s.lastTickAt=null;save();renderAll()}
function tick(){checkDay();let a=active();if(!a||s.isPaused)return;let n=Date.now();if(!s.lastTickAt)s.lastTickAt=n;let d=Math.floor((n-s.lastTickAt)/1000);if(d>0){a.seconds+=d;s.lastTickAt+=d*1000;save();renderButtons();renderTimer();renderChart()}}
function addAct(){let i=s.activities.length;s.activities.push({id:id(),name:`Attività ${i+1}`,targetMinutes:25,color:C[i%C.length],seconds:0});save();renderAll()}
function resetDay(){if(!confirm('Vuoi azzerare il tempo registrato oggi?'))return;s.activities=s.activities.map(a=>({...a,seconds:0}));syncLog();s.logs[today()]={};stopTimer()}
function renderAll(){renderSummary();renderEditor();renderButtons();renderTimer();renderPeriodButtons();renderChart()}
pause.onclick=pauseTimer;stop.onclick=stopTimer;add.onclick=addAct;reset.onclick=resetDay;checkDay();renderAll();setInterval(tick,1000);
