const K='activityTimerState.v2';
const C=['#2563eb','#7c3aed','#059669','#f59e0b','#ef4444','#0891b2','#db2777','#4f46e5','#65a30d','#c026d3'];
const id=()=>crypto.randomUUID();
const today=()=>new Date().toISOString().slice(0,10);
const def=()=>({date:today(),activeId:null,isPaused:false,lastTickAt:null,activities:[{id:id(),name:'Clinica pazienti',targetMinutes:240,color:C[0],seconds:0},{id:id(),name:'Ricerca',targetMinutes:120,color:C[1],seconds:0},{id:id(),name:'Casa',targetMinutes:30,color:C[2],seconds:0},{id:id(),name:'Relazioni sociali',targetMinutes:30,color:C[3],seconds:0},{id:id(),name:'Alimentazione',targetMinutes:60,color:C[4],seconds:0},{id:id(),name:'Allenamento',targetMinutes:45,color:C[5],seconds:0},{id:id(),name:'Tempo libero',targetMinutes:60,color:C[6],seconds:0}]});
let s=load();
const q=x=>document.querySelector(x),ed=q('#activityEditor'),bs=q('#activityButtons'),tpl=q('#activityRowTemplate'),ttl=q('#timerTitle'),el=q('#elapsedTime'),info=q('#targetInfo'),pause=q('#pauseBtn'),stop=q('#stopBtn'),add=q('#addActivityBtn'),reset=q('#resetDayBtn'),total=q('#totalTimeLabel'),leg=q('#legend'),cv=q('#pieChart'),ctx=cv.getContext('2d');
function load(){try{const x=JSON.parse(localStorage.getItem(K));return x&&x.activities&&x.activities.length?{...def(),...x,activeId:null,isPaused:false,lastTickAt:null}:def()}catch{return def()}}
function save(){localStorage.setItem(K,JSON.stringify(s))}
function esc(v){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function fmt(n){n=Math.max(0,Math.floor(n));let h=Math.floor(n/3600),m=Math.floor(n%3600/60),x=n%60;return h?`${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(x).padStart(2,'0')}`:`${String(m).padStart(2,'0')}:${String(x).padStart(2,'0')}`}
function active(){return s.activities.find(a=>a.id===s.activeId)}
function checkDay(){if(s.date!==today()){s.activities=s.activities.map(a=>({...a,seconds:0}));s.activeId=null;s.isPaused=false;s.lastTickAt=null;s.date=today();save()}}
function renderEditor(){ed.innerHTML='';s.activities.forEach(a=>{let r=tpl.content.firstElementChild.cloneNode(true),n=r.querySelector('.activity-name'),t=r.querySelector('.activity-target'),rm=r.querySelector('.remove-activity');n.value=a.name;t.value=a.targetMinutes;n.oninput=()=>{a.name=n.value.trim()||'Senza nome';save();renderButtons();renderTimer();renderChart()};t.oninput=()=>{a.targetMinutes=Math.max(1,+t.value||1);save();renderButtons();renderTimer()};rm.onclick=()=>{if(s.activities.length<2)return;if(s.activeId===a.id)stopTimer();s.activities=s.activities.filter(x=>x.id!==a.id);save();renderAll()};ed.appendChild(r)})}
function renderButtons(){bs.innerHTML='';s.activities.forEach(a=>{let b=document.createElement('button');b.type='button';b.className='big-activity-btn';b.style.background=a.color;b.classList.toggle('active',a.id===s.activeId&&!s.isPaused);b.innerHTML=`<span>${esc(a.name)}</span><span>${Math.round(a.seconds/60)} / ${a.targetMinutes} min</span>`;b.onclick=()=>start(a.id);bs.appendChild(b)})}
function renderTimer(){let a=active();pause.disabled=stop.disabled=!a;if(!a){ttl.textContent='Nessuna attività';el.textContent='00:00';info.textContent='Premi un pulsante per iniziare.';pause.textContent='Pausa';return}ttl.textContent=a.name;el.textContent=fmt(a.seconds);let rem=Math.max(0,a.targetMinutes*60-a.seconds);info.textContent=`${s.isPaused?'In pausa':'In corso'} · obiettivo ${a.targetMinutes} min · restano ${fmt(rem)}`;pause.textContent=s.isPaused?'Riprendi':'Pausa'}
function renderChart(){let sum=s.activities.reduce((p,a)=>p+a.seconds,0);total.textContent=`Totale registrato oggi: ${Math.round(sum/60)} min`;ctx.clearRect(0,0,cv.width,cv.height);let c=cv.width/2,r=cv.width*.38;if(!sum){ctx.beginPath();ctx.arc(c,c,r,0,Math.PI*2);ctx.fillStyle='#e2e8f0';ctx.fill();ctx.beginPath();ctx.arc(c,c,r*.52,0,Math.PI*2);ctx.fillStyle='white';ctx.fill();ctx.fillStyle='#64748b';ctx.font='800 26px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('0m',c,c);leg.innerHTML='<p class="target-info">La pie chart comparirà appena registri tempo.</p>';return}let st=-Math.PI/2;leg.innerHTML='';s.activities.forEach(a=>{if(a.seconds<=0)return;let sl=a.seconds/sum,en=st+sl*Math.PI*2;ctx.beginPath();ctx.moveTo(c,c);ctx.arc(c,c,r,st,en);ctx.closePath();ctx.fillStyle=a.color;ctx.fill();let p=Math.round(sl*100),it=document.createElement('div');it.className='legend-item';it.innerHTML=`<span class="legend-dot" style="background:${a.color}"></span><strong>${esc(a.name)}</strong><span>${p}% · ${Math.round(a.seconds/60)} min</span>`;leg.appendChild(it);st=en});ctx.beginPath();ctx.arc(c,c,r*.52,0,Math.PI*2);ctx.fillStyle='white';ctx.fill();ctx.fillStyle='#111827';ctx.font='900 32px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(`${Math.round(sum/60)}m`,c,c)}
function start(x){s.activeId=x;s.isPaused=false;s.lastTickAt=Date.now();save();renderAll()}
function pauseTimer(){let a=active();if(!a)return;s.isPaused=!s.isPaused;s.lastTickAt=s.isPaused?null:Date.now();save();renderAll()}
function stopTimer(){s.activeId=null;s.isPaused=false;s.lastTickAt=null;save();renderAll()}
function tick(){checkDay();let a=active();if(!a||s.isPaused)return;let n=Date.now();if(!s.lastTickAt)s.lastTickAt=n;let d=Math.floor((n-s.lastTickAt)/1000);if(d>0){a.seconds+=d;s.lastTickAt+=d*1000;save();renderButtons();renderTimer();renderChart()}}
function addAct(){let i=s.activities.length;s.activities.push({id:id(),name:`Attività ${i+1}`,targetMinutes:25,color:C[i%C.length],seconds:0});save();renderAll()}
function resetDay(){if(!confirm('Vuoi azzerare il tempo registrato oggi?'))return;s.activities=s.activities.map(a=>({...a,seconds:0}));stopTimer()}
function renderAll(){renderEditor();renderButtons();renderTimer();renderChart()}
pause.onclick=pauseTimer;stop.onclick=stopTimer;add.onclick=addAct;reset.onclick=resetDay;checkDay();renderAll();setInterval(tick,1000);if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}));
